# Generated by Django 4.2.2 on 2023-09-01 08:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cognito_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
