"""
Django Development settings for duende project.
Generated by loop developer using django 4.0(LTS) version.
all development configuration settings
"""
from datetime import timedelta

from .base import *

# rest framework authentication setup
REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend'
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'django_cognito_jwt.JSONWebTokenAuthentication',
    ],
}

# Database Settings using decouple configurations.
DATABASES = {'default': {'ENGINE': config('ENGINE'),
                         'NAME': config('DB_NAME'),
                         'PASSWORD': config('DB_PASSWORD'),
                         'USER': config('DB_USER'),
                         'HOST': config('DB_HOST'),
                         'PORT': config('DB_PORT')}, }

PROJECT_BASE_URL = config('BACKEND_BASE_URL')

# JWT configuration for manage access tokens
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=15),
    # 'ACCESS_TOKEN_LIFETIME': timedelta(days=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': config('SECRET_KEY'),
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',

    'JTI_CLAIM': 'jti',

    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}

# cognito services
# AWS Cognito Configuration
COGNITO_POOL_ID = config('COGNITO_POOL_ID')
COGNITO_APP_CLIENT = config('COGNITO_APP_CLIENT')
COGNITO_APP_CLIENT_SECRET = config('COGNITO_APP_CLIENT_SECRET')
COGNITO_REGION = config('COGNITO_REGION')
AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY')
COGNITO_AWS_REGION = config('COGNITO_REGION')
COGNITO_USER_POOL=config('COGNITO_POOL_ID')
COGNITO_AUDIENCE=config('COGNITO_APP_CLIENT')
COGNITO_CONFIG = {
    # URL consists of https://{pool-name}.auth.{region}.amazoncognito.com/oauth2/token
    # Replace it below accordingly
    "url": "https://frontenddrfcognito77b3bdee_userpool_77b3bdee-dev.auth.ap-southeast-2.amazoncognito.com/oauth2/token",
    "app_client_id": config('COGNITO_APP_CLIENT'),
    "region": config('COGNITO_REGION'),
    "aws_user_pools_id": config('COGNITO_POOL_ID'),
    "aws_user_pools_web_client_id": config('COGNITO_APP_CLIENT'),
}


# for email configuration
EMAIL_BACKEND = config('EMAIL_BACKEND')
EMAIL_USE_TLS = config('EMAIL_USE_TLS')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL')
SERVER_EMAIL = config('SERVER_EMAIL')
EMAIL_HOST = config('EMAIL_HOST')
EMAIL_PORT = config('EMAIL_PORT')
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
