"""
Django Development settings for duende project.
Generated by loop developer using django 4.0(LTS) version.
all development configuration settings
"""
from datetime import datetime
from datetime import timedelta
from decouple import config
from .base import *

# rest framework authentication setup
REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend'
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'django_cognito_jwt.JSONWebTokenAuthentication',
    ],
}

# Database Settings using decouple configurations.
DATABASES = {'default': {'ENGINE': config('ENGINE'),
                         'NAME': config('DB_NAME'),
                         'PASSWORD': config('DB_PASSWORD'),
                         'USER': config('DB_USER'),
                         'HOST': config('DB_HOST'),
                         'PORT': config('DB_PORT')}, }

PROJECT_BASE_URL = config('BACKEND_BASE_URL')

# JWT configuration for manage access tokens
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=15),
    # 'ACCESS_TOKEN_LIFETIME': timedelta(days=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': config('SECRET_KEY'),
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',

    'JTI_CLAIM': 'jti',

    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}
